# Generated by Django 3.2.9 on 2021-12-10 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('city', models.CharField(max_length=20, verbose_name='город')),
                ('address', models.CharField(max_length=50, verbose_name='адрес')),
                ('map_coordinate', models.CharField(max_length=30, verbose_name='координаты Google Maps')),
                ('phone_number', models.CharField(max_length=13, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='эл.почта')),
                ('logo_image', models.ImageField(unique=True, upload_to='cinemas/', verbose_name='логотип')),
                ('main_image', models.ImageField(unique=True, upload_to='cinemas/', verbose_name='главная картинка')),
            ],
            options={
                'verbose_name': 'кинотеатр',
                'verbose_name_plural': 'кинотеатры',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('genre', models.CharField(choices=[('action', 'Боевик'), ('comedy', 'Комедия'), ('detective', 'Детектив'), ('horror', 'Ужасы'), ('thriller', 'Триллер')], max_length=10, verbose_name='жанр')),
                ('age_limit', models.CharField(max_length=30, verbose_name='возрастное ограничение')),
                ('premiere_date', models.DateField(verbose_name='дата премьеры')),
                ('country', models.CharField(max_length=30, verbose_name='страна')),
                ('duration', models.CharField(max_length=20, verbose_name='продолжительность')),
                ('budget', models.CharField(max_length=20, verbose_name='бюджет')),
                ('director', models.CharField(max_length=100, verbose_name='режиссер')),
                ('producer', models.CharField(max_length=100, verbose_name='продюсер')),
                ('trailer_url', models.URLField(verbose_name='ссылка на трейлер')),
                ('film_format', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('4DX', '4DX'), ('IMAX', 'IMAX')], max_length=20, verbose_name='формат')),
                ('is_active', models.BooleanField(verbose_name='статус показа')),
                ('main_image', models.ImageField(unique=True, upload_to='films/', verbose_name='главная картинка')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
            },
        ),
        migrations.CreateModel(
            name='FilmBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='main_page/film_banners/')),
                ('url', models.URLField()),
                ('text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'баннеры фильмов',
                'verbose_name_plural': 'баннеры фильмов',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'галерея',
                'verbose_name_plural': 'галереи',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('row_quantity', models.IntegerField(verbose_name='кол-во рядов')),
                ('place_per_row', models.IntegerField(verbose_name='кол-во мест в ряду')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('scheme_image', models.ImageField(unique=True, upload_to='halls/', verbose_name='схема зала')),
                ('main_image', models.ImageField(unique=True, upload_to='halls/', verbose_name='главная картинка')),
            ],
            options={
                'verbose_name': 'зал',
                'verbose_name_plural': 'залы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='gallery/', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'картинка',
                'verbose_name_plural': 'картинки',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number1', models.CharField(max_length=15, verbose_name='номер телефона 1')),
                ('phone_number2', models.CharField(blank=True, max_length=15, null=True, verbose_name='номер телефона 2')),
                ('seo_text', models.TextField(verbose_name='SEO-текст')),
            ],
            options={
                'verbose_name': 'главная страница',
                'verbose_name_plural': 'главные страницы',
            },
        ),
        migrations.CreateModel(
            name='NewsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='main_page/news_banners/', verbose_name='картинка')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'баннеры новостей',
                'verbose_name_plural': 'баннеры новостей',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='дата публикации')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='ссылка на видео')),
                ('main_image', models.ImageField(unique=True, upload_to='pages/', verbose_name='главная картинка')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'страницы',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('keywords', models.CharField(max_length=100, verbose_name='keywords')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'SEO-блок',
                'verbose_name_plural': 'SEO-блоки',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('time', models.TimeField(verbose_name='время')),
                ('ticket_price', models.IntegerField(verbose_name='стоимость билета')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.film', verbose_name='фильм')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.hall', verbose_name='зал')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'расписание',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(verbose_name='ряд')),
                ('place_number', models.IntegerField(verbose_name='место')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.schedule', verbose_name='событие')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'бронирования',
            },
        ),
    ]
