# Generated by Django 3.2.9 on 2021-11-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('city', models.CharField(max_length=20, verbose_name='город')),
                ('address', models.CharField(max_length=50, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'кинотеатр',
                'verbose_name_plural': 'кинотеатры',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('genre', models.CharField(max_length=50, verbose_name='жанр')),
                ('age_limit', models.CharField(max_length=50, verbose_name='возрастное ограничение')),
                ('premiere_date', models.DateField(db_index=True, verbose_name='дата премьеры')),
                ('country', models.CharField(max_length=30, verbose_name='страна')),
                ('duration', models.CharField(max_length=20, verbose_name='продолжительность')),
                ('budget', models.CharField(max_length=20, verbose_name='бюджет')),
                ('director', models.CharField(max_length=100, verbose_name='режиссер')),
                ('producer', models.CharField(max_length=100, verbose_name='продюсер')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
                'ordering': ['-premiere_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='фамилия')),
                ('username', models.CharField(max_length=20, verbose_name='псевдоним')),
                ('email', models.EmailField(max_length=254, verbose_name='эл.почта')),
                ('phone_number', models.CharField(max_length=15, verbose_name='номер мобильного')),
                ('city', models.CharField(max_length=20, verbose_name='город')),
                ('date_of_birth', models.DateField(verbose_name='дата рождения')),
                ('hashed_password', models.CharField(max_length=100, verbose_name='пароль')),
                ('gender', models.CharField(choices=[('Man', 'Мужчина'), ('Woman', 'Женщина')], max_length=7, verbose_name='пол')),
                ('card_number', models.IntegerField(blank=True, null=True, verbose_name='номер карты')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
