# Generated by Django 3.2.9 on 2021-11-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'SEO блок', 'verbose_name_plural': 'SEO блоки'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='additional_picture4',
            field=models.ImageField(blank=True, null=True, upload_to='cms_pages/', verbose_name='доп.картинка'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='additional_picture5',
            field=models.ImageField(blank=True, null=True, upload_to='cms_pages/', verbose_name='доп.картинка'),
        ),
    ]
