# Generated by Django 3.2.9 on 2021-11-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'фильмы'},
        ),
        migrations.AlterField(
            model_name='cinema',
            name='address',
            field=models.CharField(max_length=50, unique=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='film',
            name='premiere_date',
            field=models.DateField(verbose_name='дата премьеры'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='эл.почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='номер мобильного'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='псевдоним'),
        ),
        migrations.AlterUniqueTogether(
            name='film',
            unique_together={('name', 'premiere_date')},
        ),
    ]
