# Generated by Django 3.2.9 on 2021-11-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20211114_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='additional_picture1',
            field=models.ImageField(upload_to='page_gallery/', verbose_name='доп.картинка'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='additional_picture2',
            field=models.ImageField(upload_to='page_gallery/', verbose_name='доп.картинка'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='additional_picture3',
            field=models.ImageField(upload_to='page_gallery/', verbose_name='доп.картинка'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='additional_picture4',
            field=models.ImageField(blank=True, null=True, upload_to='page_gallery/', verbose_name='доп.картинка'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='additional_picture5',
            field=models.ImageField(blank=True, null=True, upload_to='page_gallery/', verbose_name='доп.картинка'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='main_picture',
            field=models.ImageField(upload_to='page_gallery/', verbose_name='главная картинка'),
        ),
    ]
