# Generated by Django 3.2.9 on 2021-11-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20211114_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='PageGallery',
        ),
        migrations.RenameModel(
            old_name='Seo',
            new_name='PageSeo',
        ),
    ]
