# Generated by Django 3.2.9 on 2021-11-14 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20211114_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagegallery',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.pageseo'),
        ),
    ]
